# golangci-lint configuration for webhook-bridge
# Modern configuration compatible with golangci-lint v1.64+
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives

  gocyclo:
    min-complexity: 15

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/loonghao/webhook_bridge

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 20

  nestif:
    min-complexity: 4

  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign

  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK

  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/sirupsen/logrus
            desc: "logging is allowed only by logutils.Log"

linters:
  disable-all: true
  enable:
    # Core linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Style linters
    - gofmt
    - goimports
    - misspell
    - whitespace

    # Complexity linters
    - gocyclo
    - gocognit
    - funlen
    - nestif

    # Security linters
    - gosec

    # Performance linters
    - prealloc

    # Code quality linters
    - goconst
    - gocritic
    - dupl
    - unconvert
    - unparam

    # Formatting linters
    - asciicheck
    - lll
    - nakedret

    # Documentation linters
    - godot
    - godox

    # Error handling linters
    - err113

    # Dependency management
    - depguard

    # Magic numbers
    - mnd

    # Test linters
    - testpackage

    # Style consistency
    - stylecheck
    - nolintlint

issues:
  exclude-dirs:
    - vendor
    - .venv
    - node_modules
    - dist
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
        - mnd

    # Exclude known linters from partially hard-to-fix issues
    - path: cmd/
      linters:
        - mnd
        - gocognit
        - funlen

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    # Exclude godox issues for TODO comments in development
    - linters:
        - godox
      source: "TODO:"

    # Exclude protobuf generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - all

    # Exclude some linters from tools directory
    - path: tools/
      linters:
        - gocyclo
        - gocognit
        - funlen
        - mnd

  exclude-use-default: false
  max-issues-per-linter: 50  # Limit issues per linter for CI
  max-same-issues: 10        # Limit same issues

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - gocritic
      severity: warning
