server:
  host: "127.0.0.1"
  port: 8000
  dashboard_port: 8001
logging:
  level: "info"
plugins:
  directory: "example_plugins"
python:
  executor_port: 50051
  auto_install: false
dashboard:
  enabled: true