# Webhook Bridge Configuration
# This is the main configuration file for the webhook bridge unified architecture

server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release

python:
  # Python interpreter discovery strategy
  # Options: auto, uv, path, custom
  strategy: "auto"

  # Custom Python interpreter path (used when strategy is "custom")
  interpreter_path: ""

  # UV virtual environment settings
  uv:
    enabled: true
    project_path: "."  # Path to Python project with pyproject.toml
    venv_name: ".venv"

  # Plugin directories to search for Python plugins
  plugin_dirs:
    - "./plugins"
    - "./webhook_bridge/plugins"
    - "./example_plugins"

  # Environment validation settings
  validation:
    enabled: true
    min_python_version: "3.8"
    required_capabilities:
      - "sys"
      - "os"
      - "json"
    strict_mode: false
    cache_timeout: 5  # minutes

  # Auto-install missing dependencies
  auto_install: false

  # Required packages for webhook execution
  required_packages:
    - "grpcio"
    - "grpcio-tools"

executor:
  # Python executor gRPC service configuration (managed automatically by unified service)
  host: "127.0.0.1"  # Use IPv4 localhost for local development
  port: 50051
  timeout: 30  # seconds
  auto_start: true   # Automatically start Python executor in unified mode

logging:
  level: "info"  # debug, info, warn, error
  format: "text"  # text, json
  file: "logs/webhook-bridge.log"  # Log file path
  max_size: 100  # Max log file size in MB
  max_age: 30    # Max age in days
  compress: true # Compress old log files

# Storage configuration for execution tracking
storage:
  type: "sqlite"
  sqlite:
    path: "data/executions.db"
    max_connections: 10
    retention_days: 30
    enable_wal: true
    enable_foreign_keys: true

# Execution tracking configuration
execution_tracking:
  enabled: true
  max_executions: 10000
  cleanup_interval: "1h"
  retention_period: "720h"  # 30 days

# Directories configuration
directories:
  working_dir: ""
  log_dir: "logs"
  config_dir: ""
  plugin_dir: "plugins"
  data_dir: "data"

# Unified service configuration
unified:
  # Enable unified service mode (Python executor + Go server)
  enabled: true
  # Graceful shutdown timeout
  shutdown_timeout: 10  # seconds
  # Service startup order and timing
  startup:
    python_executor_delay: 3  # seconds to wait for Python executor startup
    health_check_interval: 5  # seconds between health checks

# Environment-specific overrides
# These can be overridden by environment variables:
# WEBHOOK_BRIDGE_HOST
# WEBHOOK_BRIDGE_PORT
# WEBHOOK_BRIDGE_MODE
# WEBHOOK_BRIDGE_PYTHON_PATH
