# Webhook Bridge Configuration Example
# This file shows how to configure the webhook bridge service

server:
  host: "0.0.0.0"
  port: 8000
  mode: "debug"  # debug, release
  auto_port: true

python:
  interpreter: "auto"  # auto, or path to python executable
  auto_download_uv: true
  venv_path: ".venv"

executor:
  host: "localhost"
  port: 0  # 0 for auto-assign
  timeout: 30
  auto_port: true

logging:
  level: "info"  # debug, info, warn, error
  format: "text"  # text, json
  file: ""  # empty for stdout only, or path to log file
  max_size: 100  # MB
  max_age: 30  # days
  compress: true

directories:
  working_dir: ""  # empty for current directory
  log_dir: "logs"  # relative to working_dir
  config_dir: ""  # empty for working_dir
  plugin_dir: "plugins"  # relative to working_dir
  data_dir: "data"  # relative to working_dir

# Example configurations for different scenarios:

# Development configuration:
# directories:
#   log_dir: "./dev-logs"
#   plugin_dir: "./dev-plugins"

# Production configuration:
# server:
#   mode: "release"
# logging:
#   level: "warn"
#   format: "json"
#   file: "/var/log/webhook-bridge/app.log"
# directories:
#   working_dir: "/opt/webhook-bridge"
#   log_dir: "/var/log/webhook-bridge"
#   plugin_dir: "/opt/webhook-bridge/plugins"

# Custom log directory configuration:
# directories:
#   log_dir: "/custom/log/path"  # absolute path
#   # or
#   working_dir: "/app"
#   log_dir: "custom-logs"  # relative to /app, results in /app/custom-logs
