# MkDocs configuration for Webhook Bridge
site_name: Webhook Bridge Documentation
site_description: High-performance webhook integration platform with hybrid Go/Python architecture
site_author: Webhook Bridge Team
site_url: https://loonghao.github.io/webhook_bridge

# Repository
repo_name: loonghao/webhook_bridge
repo_url: https://github.com/loonghao/webhook_bridge
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Webhook Bridge Team

# Configuration
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search:
      lang: 
        - en
        - zh
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: loonghao
      repo: webhook_bridge
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 首页: README.md
  - 用户指南:
    - CLI使用指南: CLI_USAGE.md
    - CLI快速参考: CLI_QUICK_REFERENCE.md
    - Dashboard使用指南: DASHBOARD_GUIDE.md

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/loonghao/webhook_bridge
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/webhook-bridge/
  analytics:
    provider: google
    property: G-XXXXXXXXXX

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
