# Test Configuration for Webhook Bridge
server:
  host: "127.0.0.1"
  port: 9000  # Different port for testing
  mode: "release"  # Production mode
  auto_port: false

python:
  interpreter: "auto"  # Auto-detect Python
  auto_download_uv: true
  venv_path: ".venv"
  uv:
    enabled: true
    venv_name: ".venv"
  validation:
    enabled: true
    min_python_version: "3.8"
    cache_timeout: 5
  auto_install: false
  required_packages:
    - "grpcio"
    - "grpcio-tools"

executor:
  host: "localhost"
  port: 60051  # Different port for testing
  timeout: 45
  auto_port: false

logging:
  level: "debug"  # More verbose logging
  format: "json"  # JSON format for testing
