server:
  host: "0.0.0.0"
  port: 8000
  mode: "debug"
  auto_port: true

executor:
  host: "localhost"
  port: 50051
  timeout: 30

python:
  interpreter: "python"
  auto_download_uv: true
  venv_path: ".venv"

logging:
  level: "info"
  format: "text"
  file: ""

directories:
  working_dir: "."
  log_dir: "logs"
  plugin_dir: "plugins"
  data_dir: "data"
