# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.proto import webhook_pb2 as api_dot_proto_dot_webhook__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api/proto/webhook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WebhookExecutorStub(object):
    """WebhookExecutor service for executing webhook plugins
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePlugin = channel.unary_unary(
                '/webhook.WebhookExecutor/ExecutePlugin',
                request_serializer=api_dot_proto_dot_webhook__pb2.ExecutePluginRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_webhook__pb2.ExecutePluginResponse.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/webhook.WebhookExecutor/ListPlugins',
                request_serializer=api_dot_proto_dot_webhook__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_webhook__pb2.ListPluginsResponse.FromString,
                _registered_method=True)
        self.GetPluginInfo = channel.unary_unary(
                '/webhook.WebhookExecutor/GetPluginInfo',
                request_serializer=api_dot_proto_dot_webhook__pb2.GetPluginInfoRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_webhook__pb2.GetPluginInfoResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/webhook.WebhookExecutor/HealthCheck',
                request_serializer=api_dot_proto_dot_webhook__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_webhook__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class WebhookExecutorServicer(object):
    """WebhookExecutor service for executing webhook plugins
    """

    def ExecutePlugin(self, request, context):
        """Execute a webhook plugin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """List available plugins
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPluginInfo(self, request, context):
        """Get plugin information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebhookExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePlugin,
                    request_deserializer=api_dot_proto_dot_webhook__pb2.ExecutePluginRequest.FromString,
                    response_serializer=api_dot_proto_dot_webhook__pb2.ExecutePluginResponse.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=api_dot_proto_dot_webhook__pb2.ListPluginsRequest.FromString,
                    response_serializer=api_dot_proto_dot_webhook__pb2.ListPluginsResponse.SerializeToString,
            ),
            'GetPluginInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginInfo,
                    request_deserializer=api_dot_proto_dot_webhook__pb2.GetPluginInfoRequest.FromString,
                    response_serializer=api_dot_proto_dot_webhook__pb2.GetPluginInfoResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=api_dot_proto_dot_webhook__pb2.HealthCheckRequest.FromString,
                    response_serializer=api_dot_proto_dot_webhook__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'webhook.WebhookExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('webhook.WebhookExecutor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebhookExecutor(object):
    """WebhookExecutor service for executing webhook plugins
    """

    @staticmethod
    def ExecutePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/webhook.WebhookExecutor/ExecutePlugin',
            api_dot_proto_dot_webhook__pb2.ExecutePluginRequest.SerializeToString,
            api_dot_proto_dot_webhook__pb2.ExecutePluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/webhook.WebhookExecutor/ListPlugins',
            api_dot_proto_dot_webhook__pb2.ListPluginsRequest.SerializeToString,
            api_dot_proto_dot_webhook__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPluginInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/webhook.WebhookExecutor/GetPluginInfo',
            api_dot_proto_dot_webhook__pb2.GetPluginInfoRequest.SerializeToString,
            api_dot_proto_dot_webhook__pb2.GetPluginInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/webhook.WebhookExecutor/HealthCheck',
            api_dot_proto_dot_webhook__pb2.HealthCheckRequest.SerializeToString,
            api_dot_proto_dot_webhook__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
