// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/webhook.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for executing a plugin
type ExecutePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	HttpMethod    string                 `protobuf:"bytes,2,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueryString   string                 `protobuf:"bytes,5,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePluginRequest) Reset() {
	*x = ExecutePluginRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePluginRequest) ProtoMessage() {}

func (x *ExecutePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePluginRequest.ProtoReflect.Descriptor instead.
func (*ExecutePluginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutePluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *ExecutePluginRequest) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *ExecutePluginRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecutePluginRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ExecutePluginRequest) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

// Response message for plugin execution
type ExecutePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTime float64                `protobuf:"fixed64,5,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"` // in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePluginResponse) Reset() {
	*x = ExecutePluginResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePluginResponse) ProtoMessage() {}

func (x *ExecutePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePluginResponse.ProtoReflect.Descriptor instead.
func (*ExecutePluginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutePluginResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ExecutePluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutePluginResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecutePluginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecutePluginResponse) GetExecutionTime() float64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

// Request message for listing plugins
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"` // optional filter pattern
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *ListPluginsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Response message for listing plugins
type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginInfo          `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *ListPluginsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Plugin information
type PluginInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path             string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SupportedMethods []string               `protobuf:"bytes,4,rep,name=supported_methods,json=supportedMethods,proto3" json:"supported_methods,omitempty"`
	IsAvailable      bool                   `protobuf:"varint,5,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	LastModified     string                 `protobuf:"bytes,6,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_api_proto_webhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{4}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetSupportedMethods() []string {
	if x != nil {
		return x.SupportedMethods
	}
	return nil
}

func (x *PluginInfo) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *PluginInfo) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

// Request message for getting plugin info
type GetPluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoRequest) Reset() {
	*x = GetPluginInfoRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoRequest) ProtoMessage() {}

func (x *GetPluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{5}
}

func (x *GetPluginInfoRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

// Response message for getting plugin info
type GetPluginInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        *PluginInfo            `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoResponse) Reset() {
	*x = GetPluginInfoResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoResponse) ProtoMessage() {}

func (x *GetPluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{6}
}

func (x *GetPluginInfoResponse) GetPlugin() *PluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *GetPluginInfoResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "unhealthy", "unknown"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_proto_webhook_proto protoreflect.FileDescriptor

const file_api_proto_webhook_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/webhook.proto\x12\awebhook\"\xf3\x02\n" +
	"\x14ExecutePluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x1f\n" +
	"\vhttp_method\x18\x02 \x01(\tR\n" +
	"httpMethod\x12;\n" +
	"\x04data\x18\x03 \x03(\v2'.webhook.ExecutePluginRequest.DataEntryR\x04data\x12D\n" +
	"\aheaders\x18\x04 \x03(\v2*.webhook.ExecutePluginRequest.HeadersEntryR\aheaders\x12!\n" +
	"\fquery_string\x18\x05 \x01(\tR\vqueryString\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x02\n" +
	"\x15ExecutePluginResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.webhook.ExecutePluginResponse.DataEntryR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12%\n" +
	"\x0eexecution_time\x18\x05 \x01(\x01R\rexecutionTime\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x12ListPluginsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\"e\n" +
	"\x13ListPluginsResponse\x12-\n" +
	"\aplugins\x18\x01 \x03(\v2\x13.webhook.PluginInfoR\aplugins\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xcb\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x11supported_methods\x18\x04 \x03(\tR\x10supportedMethods\x12!\n" +
	"\fis_available\x18\x05 \x01(\bR\visAvailable\x12#\n" +
	"\rlast_modified\x18\x06 \x01(\tR\flastModified\"7\n" +
	"\x14GetPluginInfoRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\"Z\n" +
	"\x15GetPluginInfoResponse\x12+\n" +
	"\x06plugin\x18\x01 \x01(\v2\x13.webhook.PluginInfoR\x06plugin\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xc8\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\adetails\x18\x03 \x03(\v2).webhook.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc5\x02\n" +
	"\x0fWebhookExecutor\x12N\n" +
	"\rExecutePlugin\x12\x1d.webhook.ExecutePluginRequest\x1a\x1e.webhook.ExecutePluginResponse\x12H\n" +
	"\vListPlugins\x12\x1b.webhook.ListPluginsRequest\x1a\x1c.webhook.ListPluginsResponse\x12N\n" +
	"\rGetPluginInfo\x12\x1d.webhook.GetPluginInfoRequest\x1a\x1e.webhook.GetPluginInfoResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.webhook.HealthCheckRequest\x1a\x1c.webhook.HealthCheckResponseB.Z,github.com/loonghao/webhook_bridge/api/protob\x06proto3"

var (
	file_api_proto_webhook_proto_rawDescOnce sync.Once
	file_api_proto_webhook_proto_rawDescData []byte
)

func file_api_proto_webhook_proto_rawDescGZIP() []byte {
	file_api_proto_webhook_proto_rawDescOnce.Do(func() {
		file_api_proto_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_webhook_proto_rawDesc), len(file_api_proto_webhook_proto_rawDesc)))
	})
	return file_api_proto_webhook_proto_rawDescData
}

var file_api_proto_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_webhook_proto_goTypes = []any{
	(*ExecutePluginRequest)(nil),  // 0: webhook.ExecutePluginRequest
	(*ExecutePluginResponse)(nil), // 1: webhook.ExecutePluginResponse
	(*ListPluginsRequest)(nil),    // 2: webhook.ListPluginsRequest
	(*ListPluginsResponse)(nil),   // 3: webhook.ListPluginsResponse
	(*PluginInfo)(nil),            // 4: webhook.PluginInfo
	(*GetPluginInfoRequest)(nil),  // 5: webhook.GetPluginInfoRequest
	(*GetPluginInfoResponse)(nil), // 6: webhook.GetPluginInfoResponse
	(*HealthCheckRequest)(nil),    // 7: webhook.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 8: webhook.HealthCheckResponse
	nil,                           // 9: webhook.ExecutePluginRequest.DataEntry
	nil,                           // 10: webhook.ExecutePluginRequest.HeadersEntry
	nil,                           // 11: webhook.ExecutePluginResponse.DataEntry
	nil,                           // 12: webhook.HealthCheckResponse.DetailsEntry
}
var file_api_proto_webhook_proto_depIdxs = []int32{
	9,  // 0: webhook.ExecutePluginRequest.data:type_name -> webhook.ExecutePluginRequest.DataEntry
	10, // 1: webhook.ExecutePluginRequest.headers:type_name -> webhook.ExecutePluginRequest.HeadersEntry
	11, // 2: webhook.ExecutePluginResponse.data:type_name -> webhook.ExecutePluginResponse.DataEntry
	4,  // 3: webhook.ListPluginsResponse.plugins:type_name -> webhook.PluginInfo
	4,  // 4: webhook.GetPluginInfoResponse.plugin:type_name -> webhook.PluginInfo
	12, // 5: webhook.HealthCheckResponse.details:type_name -> webhook.HealthCheckResponse.DetailsEntry
	0,  // 6: webhook.WebhookExecutor.ExecutePlugin:input_type -> webhook.ExecutePluginRequest
	2,  // 7: webhook.WebhookExecutor.ListPlugins:input_type -> webhook.ListPluginsRequest
	5,  // 8: webhook.WebhookExecutor.GetPluginInfo:input_type -> webhook.GetPluginInfoRequest
	7,  // 9: webhook.WebhookExecutor.HealthCheck:input_type -> webhook.HealthCheckRequest
	1,  // 10: webhook.WebhookExecutor.ExecutePlugin:output_type -> webhook.ExecutePluginResponse
	3,  // 11: webhook.WebhookExecutor.ListPlugins:output_type -> webhook.ListPluginsResponse
	6,  // 12: webhook.WebhookExecutor.GetPluginInfo:output_type -> webhook.GetPluginInfoResponse
	8,  // 13: webhook.WebhookExecutor.HealthCheck:output_type -> webhook.HealthCheckResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_webhook_proto_init() }
func file_api_proto_webhook_proto_init() {
	if File_api_proto_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_webhook_proto_rawDesc), len(file_api_proto_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_webhook_proto_goTypes,
		DependencyIndexes: file_api_proto_webhook_proto_depIdxs,
		MessageInfos:      file_api_proto_webhook_proto_msgTypes,
	}.Build()
	File_api_proto_webhook_proto = out.File
	file_api_proto_webhook_proto_goTypes = nil
	file_api_proto_webhook_proto_depIdxs = nil
}
