name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get repository name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.3.0
        with:
          with-owner: 'true'
          string-case: 'uppercase'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-3.12-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-3.12-
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          poetry --version
          poetry lock --no-update
          poetry install

      - name: Run tests and collect coverage
        run: |
          nox -s pytest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: loonghao/${{ steps.repo-name.outputs.repository-name }}
          files: 'coverage.xml'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
